apiVersion: v1
kind: Service
metadata:
  name: notes-service
  namespace: app-common-ns 

spec:
  selector:
    app: notes
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
  